# Generated by Django 5.2.17 on 2026-08-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_subject_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0-100, higher = more risk",
                        max_digits=5,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("attendance_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("avg_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("failing_subjects", models.IntegerField(default=0)),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_score"],
            },
        ),
    ]
