# Generated by Django 5.2.17 on 2026-08-15 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("core", "0005_subject_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlagiarismReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.DecimalField(
                        decimal_places=2, help_text="0-100% similarity", max_digits=5
                    ),
                ),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.assignment",
                    ),
                ),
                (
                    "submission_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plagiarism_as_a",
                        to="core.submission",
                    ),
                ),
                (
                    "submission_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plagiarism_as_b",
                        to="core.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-similarity_score"],
            },
        ),
    ]
